onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - better-sqlite3

shellEmulator: true

supportedArchitectures:
  cpu: [arm64]
  os: [darwin, linux]

storeDir: /Users/dzaitsev/.local/share/pnpm/store
